project:
  type: website

execute:
  freeze: auto

website:
  title: ""
  site-url: "https://tracyteal.com/"
  twitter-card:
    creator: "@tracykteal"
    card-style: summary_large_image
  favicon: "images/teal_favicon.png"
  navbar:
    right:
      - icon: house
        text: "Tracy Teal"
        href: index.qmd
      - text: "Resources"
        href: resources.qmd
      - icon: mastodon
        href: https://fosstodon.org/@tracykteal
      - icon: github
        href: https://github.com/tracykteal
      - icon: linkedin
        href: https://www.linkedin.com/in/tracy-teal-059136b/

format:
  html:
    theme: flatly
    linkcolor: "#009999"
    css: styles.css
    toc: true

editor: visual


