project:
  type: website

execute:
  freeze: auto

website:
  title: ""
  site-url: "https://tracyteal.com/"
  twitter-card:
    creator: "@tracykteal"
    card-style: summary_large_image
  favicon: "images/favicon_teal_sq2.png"
  navbar:
    right:
      - icon: house
        text: "Tracy Teal"
        href: index.qmd
      - text: "Resources"
        href: resources.qmd
      - icon: mastodon
        href: https://mastodon.social/@tracykteal
      - icon: github
        href: https://github.com
      - icon: linkedin
        href: https://linkedin.com

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual


