project:
  type: website

execute:
  freeze: auto

website:
  title: ""
  site-url: "https://tkteal.com/"
  twitter-card:
    creator: "@tracykteal"
    card-style: summary_large_image
  favicon: "images/teal_favicon.png"
  navbar:
    right:
      - icon: house
        text: "Tracy Teal"
        href: index.qmd
      - text: "Resources"
        href: resources.qmd
      - text: Newsletter
        href: https://buttondown.com/tkteal/archive
      - text: "{{< iconify fa6-brands:bluesky title='Bluesky'>}}"
        href: https://bsky.app/profile/tracykteal.bsky.social
      - icon: github
        href: https://github.com/tracykteal
      - icon: linkedin
        href: https://www.linkedin.com/in/tracykteal/

format:
  html:
    theme: flatly
    linkcolor: "#009999"
    css: styles.css
    toc: true

editor: visual


