---
title: "Resources"
format:
  html: 
    fontsize: 16px
    linestretch: 1.5
---

These are a few of my favorite articles and talks on career pathways, data science practices and collaboration, and data science training I've been involved with.

* [\[Video\] It's not just code: managing an open source project](https://www.youtube.com/watch?v=CiXhTA6zkjA) PyData Seattle 2023
* [\[Video\] Inclusive pedagogy to support computational teaching](https://www.youtube.com/watch?v=IYADM3-0QSM) PyCon 2019
* [\[Video\] Panel discussion: Growth and Data Science: Individuals, leaders, organizations and responsibilities](https://posit.co/resources/videos/panel-discussion-growth-and-data-science-individuals-leaders-organizations-and-responsibilities/) rstudio::conf(2019)


### Career Pathways

|                                                                                                                                                                               |                                                   |
|-------------------------------------------------|-----------------------|
| [data.org pathways to impact interview](https://data.org/news/pathways-to-impact-tracy-teal/) | Perry Hewitt, 09 March 2023 |
| [An interview with UC Berkeley QB3 Professional in Residence Tracy Teal: harnessing community to support scientific research](https://qb3.berkeley.edu/news/an-interview-with-professional-in-residence-tracy-teal-harnessing-community-to-support-scientific-research/) |  Jonathan Liu, 01 March 2021 |


## Data science practices and collaboration

|                                                                                                                                                                               |                                                   |
|-------------------------------------------------|-----------------------|
| [Ten simple rules to cultivate transdisciplinary collaboration in data science](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1008879)               | F Sahneh et al, 2021                              |
| [Good enough practices in scientific computing](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510)                                               | Wilson et al, 2017                                |
| [Computing workflows for biologists: a roadmap](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1002303)                                                | A Shade & TK Teal, 2015                           |
| [11 ways to avert a data-storage disaster](https://www.nature.com/articles/d41586-019-01040-w)                                                                                | by Jeffrey Perkel, 1 April 2019 Nature            |
| [When it comes to reproducible science, Git is code for success](https://www.nature.com/nature-index/news-blog/when-it-comes-to-reproducible-science-git-is-code-for-success) | by Jeffrey Perkel, 11 June 2018 Nature            |
| [Six tips for better spreadsheets](https://www.nature.com/articles/d41586-022-02076-1)                                                                                        | by Jeffrey Perkel, 2 August 2022 Nature (paywall) |
| [Journal of Open Source Software (JOSS): design and first-year review](https://peerj.com/articles/cs-147.pdf),                                                                | AM Smith et al, 2018                              |

## Data Science Training

|                                                                                                                                                                                                                                   |                             |
|-------------------------------------------------|-----------------------|
| [Optimizing Short-format Training: an International Consensus on Effective, Inclusive, and Career-spanning Professional Development in the Life Sciences and Beyond](https://www.biorxiv.org/content/10.1101/2023.03.10.531570v1) | JJ Williams et al, 2023     |
| [OECD Report: Building digital workforce capacity and skills for data-intensive science](https://www.research.ed.ac.uk/en/publications/building-digital-workforce-capacity-and-skills-for-data-intensive)                         | M Barker et al, 2020        |
| [Short-format workshops build skills and confidence for researchers to work with data](https://peer.asee.org/short-format-workshops-build-skills-and-confidence-for-researchers-to-work-with-data)                                | KL Jordan et al, 2018       |
| [Data carpentry: workshops to increase data literacy for researchers](http://ijdc.net/index.php/ijdc/article/view/10.1.135)                                                                                                       | Teal et al, 2015            |
| [Skills and knowledge for data-intensive environmental research](https://academic.oup.com/bioscience/article/67/6/546/3784601)                                                                                                    | SE Hampton et al, 2017      |
| [Data Science Drivers: A Report on the National Library of Medicine Workshop](https://www.nlm.nih.gov/od/osi/documents/DS_Drivers_FullReport_FINALB.pdf)                                                                          | M Zaringhalam et al, 2018   |
| [A vision for collaborative training infrastructure for bioinformatics](https://nyaspubs.onlinelibrary.wiley.com/doi/abs/10.1111/nyas.13207)                                                                                      | JJ Williams & TK Teal, 2016 |
| [Strategies for building computing skills to support microbiome analysis: a five-year perspective from the EDAMAME workshop](https://journals.asm.org/doi/full/10.1128/mSystems.00297-19)                                         | A Shade et al, 2019         |
|  [Journal of Open Source Software (JOSS): design and first-year review](https://peerj.com/articles/cs-147.pdf) | AM Smith et al, 2018 |
| [Optimizing Short-format Training: an International Consensus on Effective, Inclusive, and Career-spanning Professional Development in the Life Sciences and Beyond](https://www.biorxiv.org/content/10.1101/2023.03.10.531570v1) | JJ Williams et al, 2023 |
|  [Short-format workshops build skills and confidence for researchers to work with data](https://peer.asee.org/short-format-workshops-build-skills-and-confidence-for-researchers-to-work-with-data) | KL Jordan et al, 2018 |
| [Data carpentry: workshops to increase data literacy for researchers](http://ijdc.net/index.php/ijdc/article/view/10.1.135) | Teal et al, 2015 |
| [Skills and knowledge for data-intensive environmental research](https://academic.oup.com/bioscience/article/67/6/546/3784601) | SE Hampton et al, 2017 |
| [Data Science Drivers: A Report on the National Library of Medicine Workshop](https://www.nlm.nih.gov/od/osi/documents/DS_Drivers_FullReport_FINALB.pdf) | M Zaringhalam et al, 2018 |
| [A vision for collaborative training infrastructure for bioinformatics](https://nyaspubs.onlinelibrary.wiley.com/doi/abs/10.1111/nyas.13207) | JJ Williams & TK Teal, 2016 |
| [Strategies for building computing skills to support microbiome analysis: a five-year perspective from the EDAMAME workshop](https://journals.asm.org/doi/full/10.1128/mSystems.00297-19) | A Shade et al, 2019 |
